# Generated by Django 4.2 on 2023-04-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_auto_20230328_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='email',
        ),
    ]
