# Generated by Django 4.2 on 2023-04-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_rename_address_customer_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
